namespace CastHex
{
    public partial class Casting
    {
        private static string[] hexName = new string[] {
    "02. K'un -- Earth",
    "24. Fu -- Return",
    "07. Shih -- The Army",
    "19. Lin -- Overseeing",
    "15. Ch'ien -- Humility",
    "36. Ming I -- Concealment of Illumination",
    "46. Sheng -- Rising",
    "11. T'ai -- Tranquility",
    "16. Yu -- Enthusiasm",
    "51. Chen -- Thunder",
    "40. Hsieh -- Liberation",
    "54. Kuei Mei -- Making a Young Girl Marry",
    "62. Hsiao Kuo -- Predominance of the Small",
    "55. Feng -- Richness",
    "32. Heng -- Constancy",
    "34. Ta Chuang -- Great Power",
    "08. Pi -- Accord",
    "03. Chun -- Difficulty",
    "29. K'an -- Mastering Pitfalls",
    "60. Chieh -- Discipline",
    "39. Chien -- Halting",
    "63. Chi Chi -- Settled",
    "48. Ching -- The Well",
    "05. Hsu  -- Waiting",
    "45. Ts'ui -- Gathering",
    "17. Sui -- Following",
    "47. K'un -- Exhaustion",
    "58. Tui -- Joy",
    "31. Hsien -- Sensitivity",
    "49. Ko -- Revolution",
    "28. Ta Kuo -- Excess of the Great",
    "43. Kuai -- Parting",
    "23. Po -- Stripping Away",
    "27. I -- Lower Jaw (Nourishment)",
    "04. Meng -- Darkness",
    "41. Sun -- Reduction",
    "52. Ken -- Mountain",
    "22. Pi -- Adornment",
    "18. Ku -- Degeneration",
    "26. Ta Ch'u -- Nurturance of the Great",
    "35. Chin -- Advance",
    "21. Shih Ho -- Biting Through",
    "64. Wei Chi -- Unsettled",
    "38. K'uei -- Disharmony",
    "56. Lu -- Travel",
    "30. Li -- Fire",
    "50. Ting -- The Cauldron",
    "14. Ta Yu -- Great Possession",
    "20. Kuan -- Observation",
    "42. I -- Increase",
    "59. Huan -- Dispersal",
    "61. Chung Fu -- Faithfulness in the Center",
    "53. Chien -- Gradual Progress",
    "37. Chia Jen -- People in the Home",
    "57. Sun -- Wind",
    "09. Hsiao Ch'u -- Nurturance by the Small",
    "12. Pi -- Obstruction",
    "25. Wu Wang -- Fidelity (No Error)",
    "06. Sung -- Contention",
    "10. Lu -- Treading",
    "33. Tun -- Withdrawal",
    "13. T'ung Je^n -- Sameness with People",
    "44. Kou -- Meeting",
    "01. Chi'en -- Heaven"
    };
    }
}
