\ vim: set filetype=forth :
\ text to accompany the hexagrams...  the main program is iching.fs

64 array (hexagrams) 
: init(hexagrams) 
  0 (hexagrams) 
array$" 1.  Chi\'en -- Heaven"
array$" 2.  K\'un -- Earth"
array$" 3.  Chun -- Difficulty" 
array$" 4.  Meng -- Darkness" 
array$" 5.  Hsu  -- Waiting" 
array$" 6.  Sung -- Contention" 
array$" 7.  Shih -- The Army" 
array$" 8.  Pi -- Accord" 
array$" 9.  Hsiao Ch\'u -- Nurturance by the Small" 
array$" 10. Lu -- Treading" 
array$" 11. T\'ai -- Tranquility" 
array$" 12. Pi -- Obstruction" 
array$" 13. T\'ung Je^n -- Sameness with People" 
array$" 14. Ta Yu -- Great Possession" 
array$" 15. Ch\'ien -- Humility" 
array$" 16. Yu -- Enthusiasm"  
array$" 17. Sui -- Following"  
array$" 18. Ku -- Degeneration" 
array$" 19. Lin -- Overseeing" 
array$" 20. Kuan -- Observation" 
array$" 21. Shih Ho -- Biting Through." 
array$" 22. Pi -- Adornment" 
array$" 23. Po -- Stripping Away" 
array$" 24. Fu -- Return" 
array$" 25. Wu Wang -- Fidelity (No Error)" 
array$" 26. Ta Ch\'u -- Nurturance of the Great" 
array$" 27. I -- Lower Jaw (Nourishment)" 
array$" 28. Ta Kuo -- Excess of the Great" 
array$" 29. K\'an -- Mastering Pitfalls" 
array$" 30. Li -- Fire" 
array$" 31. Hsien -- Sensitivity"
array$" 32. Heng -- Constancy"
array$" 33. Tun -- Withdrawal"
array$" 34. Ta Chuang -- Great Power"
array$" 35. Chin -- Advance"
array$" 36. Ming I -- Concealment of Illumination"
array$" 37. Chia Jen -- People in the Home"
array$" 38. K\'uei -- Disharmony"
array$" 39. Chien -- Halting"
array$" 40. Hsieh -- Liberation"
array$" 41. Sun -- Reduction"
array$" 42. I -- Increase"
array$" 43. Kuai -- Parting"
array$" 44. Kou -- Meeting"
array$" 45. Ts\'ui -- Gathering"
array$" 46. Sheng -- Rising"
array$" 47. K\'un -- Exhaustion"
array$" 48. Ching -- The Well"
array$" 49. Ko -- Revolution"
array$" 50. Ting -- The Cauldron"
array$" 51. Chen -- Thunder"
array$" 52. Ken -- Mountain"
array$" 53. Chien -- Gradual Progress"
array$" 54. Kuei Mei -- Making a Young Girl Marry"
array$" 55. Feng -- Richness"
array$" 56. Lu -- Travel"
array$" 57. Sun -- Wind"
array$" 58. Tui -- Joy"
array$" 59. Huan -- Dispersal"
array$" 60. Chieh -- Discipline"
array$" 61. Chung Fu -- Faithfulness in the Center"
array$" 62. Hsiao Kuo -- Predominance of the Small"
array$" 63. Chi Chi -- Settled"
array$" 64. Wei Chi -- Unsettled"
  drop ;

8 array (trigrams) 
: init(trigrams)
  0 (trigrams) 
  array$" K'UN / RECEPTIVE / EARTH      "   
  array$" CHEN / AROUSING / THUNDER     "  
  array$" K'AN / ABYSMAL / WATER        "   
  array$" TUI / JOYOUS / LAKE           "     
  array$" KEN / KEEPING STILL / MOUNTAIN"  
  array$" LI / CLINGING / FIRE          "  
  array$" SUN / GENTLE / WIND           "     
  array$" CH'IEN / CREATIVE / HEAVEN    "  
  drop ;

128 array (descriptions)
: init(descriptions)
  0 (descriptions) 
( 01 ) array$" One of the four timeless hexagrams; pure yang, it"
array$" represents strength, firmness, primal unified energy."
( 02 ) array$" One of the four timeless hexagrams; pure yin; represents"
array$" receptivity, humility, obedience, yielding, flexibility, essence."
( 03 ) array$" Beginning to foster strength of primal energy, the difficult"
array$" process of breaking out of acquired temporal conditioning."
( 04 ) array$" Starting yin-convergence, making unruly yin submit, integrating"
array$" with the world yet preventing mundanity from taking over. Innocence."
( 05 ) array$" Waiting for the proper timing in gathering primal energy."
array$" Gradually restoring the primordial in the midst of the temporal."
( 06 ) array$" Depening on strength because of danger, causing danger by depending"
array$" on strength. Conflict due to imbalance."
( 07 ) array$" Using the primordial to repel conditioning, using the real"
array$" to get rid of the false."
( 08 ) array$" Learning through association; obedience in danger, rectification of"
array$" imbalance."
( 09 ) array$" Nurturing inner strength by outward submissiveness, being firm but"
array$" not impetuous, growing through humility."
( 10 ) array$" Progress; advance of the positive, prevention of danger by caution,"
array$" empowerment by calmness and trust."
( 11 ) array$" Harmony of strength and flexibility." 
array$" "
( 12 ) array$" Submitting inwardly to personal desire, acting aggressive" 
array$" outwardly."
( 13 ) array$" Mixing in with the ordinary world, concealing illumination,"
array$" assimilating to others."
( 14 ) array$" Mutual enhancement of strength and lucidity; continuous renewal,"
array$" inward discipline."
( 15 ) array$" Inwardly firm, outwardly flexible, having personal attainment"
array$" but not dwelling on it."
( 16 ) array$" Proper timing in action." 
array$" "
( 17 ) array$" According to conditions, going along with human desire to"
array$" gradually introduce guidance."
( 18 ) array$" Correcting degeneration by abandoning the false and returning"
array$" to the true."
( 19 ) array$" Keeping watch over the restoration and growth of primal energy"
array$" and repulsioin of acquired energy of conditioning."
( 20 ) array$" Alertness, gradually progressing through receptivity to the"
array$" requirements of the time, inner vigilance."
( 21 ) array$" Investigating things and finding out principles." 
array$" "
( 22 ) array$" Private cultivation, without ostentation, mutual complementarity"
array$" of clarity and stillness."
( 23 ) array$" Submission to desire, acquired mundanity dissolving away the"
array$" celestial energy."
( 24 ) array$" Return of consciousness of reality, activity obeying the mind." 
array$" "
( 25 ) array$" Vigorous advancement of celestial energy, attention to reality." 
array$" "
( 26 ) array$" Being able to be still when strong; practicing nondoing to"
array$" nurture encipient enlightenment."
( 27 ) array$" Discernment of good, becoming empty to seek fulfillment." 
array$" "
( 28 ) array$" Following desires, delighting in externals, inability to"
array$" control strength."
( 29 ) array$" One of the four timeless hexagrams; restoring the celestial"
array$" within the mundane."
( 30 ) array$" One of the four timeless hexagrams; illumination with inner" 
array$" openness."
( 31 ) array$" Harmonization of the celestial and the earthly." 
array$" "
( 32 ) array$" Singleminded application, perseverance in real practice." 
array$" "
( 33 ) array$" Storing positive energy, subduing energy, exercising strength"
array$" with restraint, not using power arbitrarily."
( 34 ) array$" Promoting vigorous positive energy; ability to act or not act,"
array$" at will; transcendence of ordinary capacities."
( 35 ) array$" Clearminded sincerity advancing illumination." 
array$" "
( 36 ) array$" Withdrawing effort after illumination, not using illumination"
array$" lightly; being enlightened yet conforming to the times."
( 37 ) array$" Governing th einner: refining the self, mastering the mind,"
array$" turning the attention inward."
( 38 ) array$" Focus on externals; requires inner emptiness to restore harmony." 
array$" "
( 39 ) array$" Preserving the primordial in the midst of the temporal." 
array$" "
( 40 ) array$" Taking advantage of the appropriate time to liberate positive"
array$" primordial energy from influences of negative, conditioned energy."
( 41 ) array$" Removing acquired conditioning, stilling mundane attraction." 
array$" "
( 42 ) array$" Entering the Dao gradually, without either rushing or lagging,"
array$" increasing the positive while decreasing the negative."
( 43 ) array$" Detachment from discriminating consciousness, repelling the"
array$" energy of external influences."
( 44 ) array$" Warding off negative influences, preserving the positive." 
array$" "
( 45 ) array$" Unifying vitality, energy, and spirit." 
array$" "
( 46 ) array$" Climbing from lowliness to the heights; carefully watching over"
array$" the development process."
( 47 ) array$" Refining body and mind." 
array$" "
( 48 ) array$" Accumulation of effort to cultivate character; nurturance of" 
array$" others"
( 49 ) array$" Refining personal desires to become unselfish." 
array$" "
( 50 ) array$" Refining illumination." 
array$" "
( 51 ) array$" Practicing introspection in action." 
array$" "
( 52 ) array$" Nurturing energy by quietude." 
array$" "
( 53 ) array$" Gradual practice following appropriate order." 
array$" "
( 54 ) array$" Seeing the real within the false." 
array$" "
( 55 ) array$" Balance of understanding and action, preventing danger by awareness." 
array$" "
( 56 ) array$" Stabilizing and nurturing illumination, transcending the world." 
array$" "
( 57 ) array$" Progress by flexible obedience." 
array$" "
( 58 ) array$" Communion of the inward and the outward; joy in practicing the Dao." 
array$" "
( 59 ) array$" Confusion of yin and yang followed by reordering." 
array$" "
( 60 ) array$" Being able to be joyful even in trouble; practicing obedience in"
array$" trying circumstances, adaptably keeping to the Dao."
( 61 ) array$" Avoidance of both obsession and negligence, seeking fulfillment by"
array$" becoming empty."
( 62 ) array$" Being fulfilled but acting empty; inwardly strong, outwardly"
array$" yielding; inwardly firm, outwardly flexible."
( 63 ) array$" Mutual completion of yin and yang; forestalling danger to stabilize"
array$" attainment."
( 64 ) array$" Refining the self, repelling mundanity, waiting for the time to"
array$" restore the primordial celestial positivity."
  drop ;
