.TH castgeo "1" "13 February 2017" "" "Utility"

.SH NAME
castgeo \- cast a geomantic shield.

.SH SYNOPSIS
.B castgeo 

.SH DESCRIPTION
castgeo generates a geomantic shield,
and displays the resulting figures on the terminal.

.SH META
This manual page is woefully incomplete. I need to add a short
description of how the shield is constructed.

.SH AUTHOR
Richard Todd (richard.weslty.todd@gmail.com)

.SH "SEE ALSO"
.BR casthex (1)
.BR iching (1)

